// The prose an author or an agent reads, generated from the same records the checks run.
//
// A rule written twice — once as a check, once as advice — is two rules that will disagree, and
// the advice is the one an agent reads. So both come from RULES in rules.mjs: `rulesMarkdown()` is
// RULES.md, and `agentGuide()` is the AGENTS.md that `vanilla-mvc init` writes and
// `vanilla-mvc guide` refreshes.
import { RULES } from './rules.mjs';

const fence = (code) => `\`\`\`ts\n${code}\n\`\`\``;

/** Every rule, one section each: what it says, why, wrong, right. */
export function rulesMarkdown() {
  const sections = RULES.map((r, i) => [
    `### ${i + 1}. ${r.says}`,
    '',
    r.why,
    '',
    'Wrong:',
    fence(r.wrong),
    'Right:',
    fence(r.right),
    '',
    `<sub>rule \`${r.id}\` · ${r.name({ within: ['vanilla-mvc', 'src/'] })}</sub>`,
  ].join('\n'));
  return [
    '<!-- Generated from architecture/rules.mjs. Do not edit: change the rule, then `npm run rules:md`. -->',
    '# The rules',
    '',
    `These ${RULES.length} rules are what make a vanilla-mvc application what it is. They are not advice:`,
    '`vanilla-mvc/architecture` checks every one of them over your source, on the syntax tree.',
    '',
    ...sections.flatMap((s) => [s, '']),
  ].join('\n');
}

/**
 * The guide an agent reads before it writes code in an application on this framework. Ordered by
 * what goes wrong first: the idiom every other library teaches is the one mistake here that
 * compiles and draws nothing, so it leads.
 */
export function agentGuide({ name = 'this application' } = {}) {
  return `<!-- Generated by \`vanilla-mvc guide\`. Do not edit: it is refreshed from the installed framework. Put your own notes in a separate file. -->
# Working on ${name}

${name} is built on **vanilla-mvc**: MVC, an event bus, and change that is *stated*, never detected.
It is not React, Vue, Svelte or lit, and the habits from those are the mistakes here. Read this
before writing code.

## The one that compiles and does nothing

A DOM handler is registered in the controller, then bound **by name** in the template:

${fence(`// controller
protected override onInterconnect(): void {
  this.handle('save', this.#save);
}
#save(): void {
  this.domain.notes.save(this.model.draft);   // a gesture goes to the application domain
}

// template
html\`<button @click=\${c.handler('save')}>Save</button>\``)}

Never \`@click=\${() => c.save()}\`. The framework refuses it when the template is built, with a
TypeError that says this. \`prevent()\`, \`field()\`, \`formValues()\` and \`keys()\` keep the registration
of the handler they wrap.

## The loop every feature is

1. A **gesture** — a registered DOM handler — calls a **capability** on the application domain.
2. The capability changes what it owns and **publishes a fact**: an event, plain data.
3. A controller **subscribed** to that fact maps it onto its **model** and calls \`this.changed()\`.
4. The gesture ends; the framework draws everything that said it changed, once.

A handler never writes the model. A model write nobody states with \`changed()\` is never drawn.
Work that waits (a promise) is returned from the handler, or handed to \`this.own()\`.

## Where things go

| Thing | Where | Make it with |
|---|---|---|
| A component | \`src/components/<name>/\`: \`.model.ts\` (types only), \`.controller.ts\`, \`.template.ts\`, \`.component.ts\`, \`.style.ts\` | \`npx vanilla-mvc add component <name>\` |
| An event | \`src/events/<name>.ts\`: one interface, \`readonly type\` equal to its name | \`npx vanilla-mvc add event <Name>\` |
| A capability | \`src/application/<name>.ts\`, adopted in \`ApplicationDomain.onCreate\` with \`this.adopt(…)\` | \`npx vanilla-mvc add capability <name>\` |

Use the generators. They write the shape the rules below check for.

## Before you say it is done

\`npm test\` — it runs \`test/architecture.test.mjs\`, which checks every rule below over \`src/\`.
A red rule names the file and line.

## The rules

${RULES.map((r, i) => `${i + 1}. **${r.says}** ${r.why}`).join('\n')}

Wrong and right for each: \`npx vanilla-mvc rules\`.
`;
}
